"""
中国房地产相关上市公司列表
涵盖A股、港股、美股市场
包含：房地产开发、物业管理、房产服务等细分领域
"""

REAL_ESTATE_STOCKS = [
    # ========== A股（20只）==========
    {"code": "001979", "name": "招商蛇口", "market": "A"},
    {"code": "600048", "name": "保利发展", "market": "A"},
    {"code": "600895", "name": "张江高科", "market": "A"},
    {"code": "600663", "name": "陆家嘴", "market": "A"},
    {"code": "601155", "name": "新城控股", "market": "A"},
    {"code": "002244", "name": "滨江集团", "market": "A"},
    {"code": "600848", "name": "上海临港", "market": "A"},
    {"code": "600007", "name": "中国国贸", "market": "A"},
    {"code": "600064", "name": "南京高科", "market": "A"},
    {"code": "600383", "name": "金地集团", "market": "A"},
    {"code": "600648", "name": "外高桥", "market": "A"},
    {"code": "601512", "name": "中新集团", "market": "A"},
    {"code": "600649", "name": "城投控股", "market": "A"},
    {"code": "001914", "name": "招商积余", "market": "A"},
    {"code": "600639", "name": "浦东金桥", "market": "A"},
    {"code": "600325", "name": "华发股份", "market": "A"},
    {"code": "600266", "name": "城建发展", "market": "A"},
    {"code": "600736", "name": "苏州高新", "market": "A"},
    {"code": "000560", "name": "我爱我家", "market": "A"},

    # ========== 港股（34只）==========
    {"code": "00016", "name": "新鸿基地产", "market": "HK"},
    {"code": "01109", "name": "华润置地", "market": "HK"},
    {"code": "01113", "name": "长实集团", "market": "HK"},
    {"code": "00012", "name": "恒基地产", "market": "HK"},
    {"code": "00688", "name": "中国海外发展", "market": "HK"},
    {"code": "02423", "name": "贝壳-W", "market": "HK"},
    {"code": "01972", "name": "太古地产", "market": "HK"},
    {"code": "00083", "name": "信和置业", "market": "HK"},
    {"code": "01209", "name": "华润万象生活", "market": "HK"},
    {"code": "01997", "name": "九龙仓置业", "market": "HK"},
    {"code": "00004", "name": "九龙仓集团", "market": "HK"},
    {"code": "00960", "name": "龙湖集团", "market": "HK"},
    {"code": "00101", "name": "恒隆地产", "market": "HK"},
    {"code": "00683", "name": "嘉里建设", "market": "HK"},
    {"code": "01908", "name": "建发国际集团", "market": "HK"},
    {"code": "03900", "name": "绿城中国", "market": "HK"},
    {"code": "00017", "name": "新世界发展", "market": "HK"},
    {"code": "00010", "name": "恒隆集团", "market": "HK"},
    {"code": "02602", "name": "万物云", "market": "HK"},
    {"code": "00014", "name": "希慎兴业", "market": "HK"},
    {"code": "06098", "name": "碧桂园服务", "market": "HK"},
    {"code": "00817", "name": "中国金茂", "market": "HK"},
    {"code": "00123", "name": "越秀地产", "market": "HK"},
    {"code": "06049", "name": "保利物业", "market": "HK"},
    {"code": "01030", "name": "新城发展", "market": "HK"},
    {"code": "00363", "name": "上海实业控股", "market": "HK"},
    {"code": "02669", "name": "中海物业", "market": "HK"},
    {"code": "02869", "name": "绿城服务", "market": "HK"},
    {"code": "00754", "name": "合生创展集团", "market": "HK"},
    {"code": "00081", "name": "中国海外宏洋集团", "market": "HK"},
    {"code": "00119", "name": "保利置业集团", "market": "HK"},
    {"code": "03990", "name": "美的置业", "market": "HK"},
    {"code": "09979", "name": "绿城管理控股", "market": "HK"},
    {"code": "02156", "name": "建发物业", "market": "HK"},

    # ========== 美股（7只）==========
    {"code": "WELL", "name": "WELLTOWER信托", "market": "US"},
    {"code": "PLD", "name": "安博(PROLOGIS)", "market": "US"},
    {"code": "EQIX", "name": "易昆尼克斯(EQUINIX)", "market": "US"},
    {"code": "AMT", "name": "美国电塔(AMERICAN TOWER)", "market": "US"},
    {"code": "SPG", "name": "西蒙地产(SIMON PROPERTY)", "market": "US"},
    {"code": "CBRE", "name": "世邦魏理仕(CBRE)", "market": "US"},
    {"code": "BEKE", "name": "贝壳", "market": "US"},
]
